name: Pull Request Update

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: viamrobotics/js-config/.github/actions/setup@618c7955f0a8261bb3cc783f2b26fcc2c9bffa3d
        with:
          node-version: 20

      - name: Lint/format checks
        run: pnpm run lint

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: viamrobotics/js-config/.github/actions/setup@618c7955f0a8261bb3cc783f2b26fcc2c9bffa3d
        with:
          node-version: 20

      - name: Type checks
        run: pnpm run check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: viamrobotics/js-config/.github/actions/setup@618c7955f0a8261bb3cc783f2b26fcc2c9bffa3d
        with:
          node-version: 20

      - name: Tests
        run: pnpm run test-run
